### ISSUE TITLE
Invalid argument order for assertEquals

### ISSUE THREAD

**Issue by klimkin** [udacity/Sunshine-Version-2#98] opened 2015-12-01 08:12 UTC
At TestUriMatcher.java#L48:

```
    assertEquals("Error: The WEATHER URI was matched incorrectly.",
            testMatcher.match(TEST_WEATHER_DIR), WeatherProvider.WEATHER);
```

Produces confusing assertion message. The argument order is wrong. Should be:

```
assertEquals(String message, int expected, int actual)
```

**Comment by edersondonde** [comment] 2015-12-27 00:02
Duplicate of #58.

**Closed as completed** 2021-02-10 16:41 UTC
